### ISSUE TITLE
Grief Prevention Confliction

### ISSUE THREAD

**Issue by bschofield1333** [graywolf336/CasinoSlots#53]
Greetings from ImbriumMC (direwolf 1.0.25  MCx1.6.4)
We are allowing players to use managed casinos and put them in there claims.  The only problem is we can't seem to get other players to be able to use it. We ruled out lwc, but we are wondering where we can find a config or other answer may alie to a solution.  In testing admins can obviously use it but anyone that is not allowed to build in claim cant use it. Or if there is a way to change the noteblock to something.
Any insight or direction would be greatly appreciated so we can fully advertise your plugin.
Thanks in advance
Brandon, Staff of ImbriumMC

**Comment by graywolf336** [comment]
@bschofield1333 Closing, please reopen if you still have issues with the latest versions.
