### ISSUE TITLE
ticket on the behalf of masitnos

### ISSUE THREAD

**Issue by topdog4life** [graywolf336/CasinoSlots#57]
Hey I dug deeper into it myself and noticed what is wrong the [player] variable is not working whenever it executes the command it would do a command like this trough console: give [player] 336 1. thereby messing up the command giving the unkown command issue.

I would call it small but it's actually a gamebreaking issue for our server. As of late the commands stopped working once they got a roll so I went in and tested. Now it seems the plugins puts in wrong commands be it pixelmon commands that worked before or well even vanilla commands. It would be great if i could get some help on this.

Here is that part out of my latest.log where you can see it states learn to command otherwise known as unkown command: http://pastebin.com/DfmuPnB4

And here is my config file: http://pastebin.com/ccJqaQkM

Would love to get some help with this thanks in advance!

Edit: Forgot to add we're running on 1.7.10

**Comment by graywolf336** [comment]
Which version exactly of the plugin? Just curious since I have a beta build out there and I'm not sure if that's what you're using or not.

**Comment by topdog4life** [comment]
we are useing CasinoSlots-2.6.0-20150103.230902-3

**Comment by graywolf336** [comment]
Is that the name of the file or the output from the game? Cause I've never
seen that version naming scheme for this plugin...

**Comment by topdog4life** [comment]
its the jar file

**Comment by graywolf336** [comment]
Can you get me the version output from the command? /ver CasinoSlots

**Comment by topdog4life** [comment]
masitnos told me to give ya this link http://gyazo.com/88b2edd967b63e417adf50a76a4b39c2

**Comment by graywolf336** [comment]
Okay thanks, will look into it possibly tomorrow or the day after.

**Comment by topdog4life** [comment]
ok thank you

**Comment by graywolf336** [comment]
Just fixed this issue, if you don't mind testing with the newest build that'd be great!

**Comment by Hektik** [comment]
I seem to have a similar problem with it or am not implementing the action command string right. I've even used copies of other configs with no success

**Comment by graywolf336** [comment]
Are you using the most recent development build to see if it is fixed? If
not, can you?

**Comment by Hektik** [comment]
I am running 2.5.7 on a Cauldron server running Pixelmon on MC 1.7.10. Other then that there are no 'large mods' and from what I read here I thought the 2.5.7 included the fix for the player tag and I don't see a download for the 2.6.0 zip. Can I download the 'master' file from here rename it to jar and use it as the core? The Action: Command is working but no commands register after that all say 'unknown command'. Should I move this to another forum? Don't want to clog up your 'fixed' pages. Thank you for your quick reply last time Would love to have these set up for our servers. Happy to help with what testing I can.

**Comment by graywolf336** [comment]
No worries, i haven't been releasing them on GitHub but on my Jenkins
server located here: http://ci.graywolf336.com/job/CasinoSlots/

Try that one and let me know if it works.

**Comment by Hektik** [comment]
Ok Downloaded and Updated it did not reset the config on reload so thats nice I was having that issue as well and had deleted the config from the jar for my temp fix. It is now saying the command is correct and it puts the player name in then returns with 'can not find player'

**Comment by Hektik** [comment]
[15:00:41] [Server thread/INFO]: [CasinoSlots] [Debug] Command for Elite4: pokegiveegg §4SuperBalzs§r random
[15:00:41] [Server thread/INFO]: Invalid Name! Try again.

If I put in my handle ' SuperBalzs ' then the command runs just fine however using [player] it gives me this. Also is there any way to make it do multiple rewards. Such as some of an item Plus another item as one 'win'?

**Comment by graywolf336** [comment]
Do you have a plugin which sets people's names to colors? If so, that's
what is causing the issue. The current setup allows for multiple actions to
be ran.

**Comment by Hektik** [comment]
Ahh. My friend owns this little server and just last night he tried to 'color' our names for us and that may be the issue I will now undo all his wasted efforts. ( wasted because it didn't work anyway ) . How would I make it have multiple rewards when I give it to item ID's serperated by comma it doesn't take.

**Comment by Hektik** [comment]
The nametag color is a default of the server and I told it to remove them but it will not. Is there a plugin that may override it and allow Casino to do its job if not I will continue trying to remove them. Also still not sure how to get multiple rewards out from one winning action.

**Comment by Hektik** [comment]
I believe the colored name tags is part of Essentials which came with my bukkit version. So the Casino is not compatible with that ? Also still no clue how to set up the multiple give commands if you wouldn't mind shedding a little light on the subject.

**Comment by graywolf336** [comment]
Please create a new ticket for the colored names issue, as it's a completely unrelated to this issue. As for the multiple actions, please look at the [default config for an example](https://github.com/graywolf336/CasinoSlots/blob/master/src/main/resources/config.yml#L103).
