### ISSUE TITLE
Problem with colored names

### ISSUE THREAD

**Issue by Hektik** [graywolf336/CasinoSlots#62]
It appears that the bukkit colored name tags interfere with the [Player] for "Action: commands". Thank you for all your help on the previous matter, with access to the commands line working properly again I figured it out. I believe it is in the 'essentials' basic set up to have Admin set to a Red tag once that is removed it cleared up. I am now trying to implement PermissionsEx and see if color tags there are treated the same.

**Comment by graywolf336** [comment]
The commit I just did should fix problems you was having with colored
names. Try the latest build and let me know if it doesn't work.

**Comment by Hektik** [comment]
So I got out Permissions EX up and when I tried the [Playername] it takes my 'Group' from PEX and uses it as my name then uses my name as the item to be given it seems. Where the long string is just a colored 'Jester' tag. Is this some Error on my side that I can clean up or can you make it ignore the group tags? 
: CONSOLE issued server command: /give §0[§aJ§4e§fst§4e§aR§0]§f §eSuperBalzs§r 264 10
: Error: Unknown item name: superbalzs.

**Comment by graywolf336** [comment]
You need to use [player] even giving items in commands and [playername]
when broadcasting a message with a command.

**Comment by Hektik** [comment]
I see that now my Apologies I had literally just tried that and it came out perfectly. Thank you very much for all the help. Love the plugin glad you support it so well.

**Comment by graywolf336** [comment]
No problem, glad i could be of help! Let me know if you have any other problems or questions.
