### ISSUE TITLE
Not Loading Config

### ISSUE THREAD

**Issue by BananaGamess** [graywolf336/CasinoSlots#63]
The config is not loading and once it doesn't load, it just get disabled when starting up, it give me a message say this 
- 12.05 19:51:24 [Server] INFO Enabling CasinoSlots v2.5.7-b11
- 12.05 19:51:24 [Server] INFO Please make sure your slots in the config file contains 'messages:'.
- 12.05 19:51:24 [Server] WARN [CasinoSlots] PLEASE CHECK ONE OF YOUR CONFIG FILES
- 12.05 19:51:24 [Server] INFO Disabling CasinoSlots v2.5.7-b11

Here are my configs:

config.yml: https://gist.github.com/BananaGamess/0118d8110d554543d9ac
Slots.yml: (Nothing, I did delete this yml because I was getting the same error)
Stats.yml: https://gist.github.com/BananaGamess/263c4d98d04a5095f836

If there is any way of fixing this, that would be greatly appreciated,

Thank you for Reading.

- BananaGamess - Solarcraft Owner

**Comment by graywolf336** [comment]
Your config is messed up. The 'messages' section of the config is not
correctly indented. Remove it back one indention and you'll be good (I
think):
https://gist.github.com/BananaGamess/0118d8110d554543d9ac#file-gistfile1-txt-L77-L96

**Comment by BananaGamess** [comment]
Thanks! It did work. It's just me being a noob :D

**Comment by graywolf336** [comment]
Awesome glad to hear! :)
