### ISSUE TITLE
Doesnt like pixelmon?

### ISSUE THREAD

**Issue by ferengi4** [graywolf336/CasinoSlots#64]
I have tried many work arounds to get casino slots to work with pixelmon commands. From using mycommand to have the console run the command, to giving players fake permissions to able to use the very command that casino slots uses. I also tried [Player] and $arg1 neither worked. I don't know if its something with your plugin or with pixelmon but any advice would be great. Your plugin is something we have used since 1.6.4 and ever since then this has been a issue.

**Comment by graywolf336** [comment]
Try the latest developer build located on my Jenkins. Let me know if it
still doesn't work then.

**Comment by ferengi4** [comment]
Worked perfectly, thanks :D I should have tried that first before posting oops.

**Comment by graywolf336** [comment]
Glad to hear! :smile:
