### ISSUE TITLE
Command sending problem

### ISSUE THREAD

**Issue by Lou363** [graywolf336/CasinoSlots#66]
Hello,
In the action line, when player won, they don't get the reward command run:
        action: command points give [player] 5
And the command is /points give [player] [amount]

**Comment by graywolf336** [comment]
What version are you running?

**Comment by Lou363** [comment]
The latest version of both plugins.

**Comment by graywolf336** [comment]
"Latest version" isn't very descriptive to me, please output what it gives you when you do: `/version CasinoSlots`

**Comment by Lou363** [comment]
Hello,
I have been very rude to answer after 18 days; I was in holidays.
This is the output:
[17:13:52]	[Server thread/INFO] : Author: [graywolf336, Darazo]
[17:13:52]	[Server thread/INFO] : Real slot machines for your server.
[17:13:52]	[Server thread/INFO] : CasinoSlots[0;37;1m version 2.5.7-b11

**Comment by graywolf336** [comment]
I'll be releasing an updated version in the next week which fixes it.
Basically in the version you're using the variable [player] contains their
display name and if that's used to display their prefix commands won't
work. That's fixed in development builds and will be released here soon.

**Comment by Lou363** [comment]
Hello again,
Can you also fix the broadcast bug; my server is broadcasting the victory so many time. Also, I have some ideas (I know I am very annoying!):
* Maybe more sounds effect while rolling the machine and music particle around the music box.
* Player Point rewards ?
* Custom sounds in the config ?
* If you won several line in the same time you get only one message which add up all rewards.
* Select a region which show up a scoreboard with your stat:
  - How much did you spend and won
  - Your average winning percentage
  - And the top 3 players which won the most.
* Made more clear the winning chance and add a lot of notes in the config file.
* Signs which show up if it is used, the cost, the type and a lot more...
* While rolling, barAPI start showing some funny things...

That was just some ideas :-)

Thank you

**Comment by Lou363** [comment]
It has been much more than a week when is the next update ?

**Comment by bschofield1333** [comment]
Unsubscribe

**Comment by graywolf336** [comment]
@Lou363 The build has been on my jenkins for a while. The public release though won't come out for a while, got a few things I want to get done before pushing it out.

As for all your suggestions, please create a separate issue for each of them *and* provide details about them.
