### ISSUE TITLE
Casinoslot not paying up, get's in a lockdown with 'This slotmachine is already in use' message.

### ISSUE THREAD

**Issue by MrKiller01** [graywolf336/CasinoSlots#70]
I found after long search this thread in my server logs.....
[19:25:48] [Server thread/INFO]: Mr_Killer01 issued server command: /casino
[19:26:02] [Server thread/INFO]: Mr_Killer01 issued server command: /casino withdraw 5000
[19:26:11] [Server thread/INFO]: Mr_Killer01 issued server command: /casino withdraw Slot1 5000
[19:26:42] [Server thread/WARN]: [CasinoSlots] Task #2947 for CasinoSlots v2.6.0-SNAPSHOT-b50 generated an exception
java.lang.NumberFormatException: For input string: "267,16,5"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_66]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_66]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_66]
	at com.craftyn.casinoslots.slot.RewardData.executeAction(RewardData.java:77) ~[?:?]
	at com.craftyn.casinoslots.slot.RewardData.send(RewardData.java:53) ~[?:?]
	at com.craftyn.casinoslots.slot.game.ResultsTask.run(ResultsTask.java:56) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
[19:32:10] [Server thread/INFO]: CONSOLE issued server command: /list

**Comment by AnHonorableHobo** [comment]
I've had this problem where the machine wont work, just reload the plugin. It works for me

**Comment by MrKiller01** [comment]
No, that's not a solution HonorableHobo, it's a work-around and i think the winnings can't pay-out and trying in a loop and never comes out of it... If i had this problem, no worries, i can unload and load the plugin, you wouldn't want all your visitors lead by hand through that everytime.... I'm still tinkering with this, so maybe i can change winnings only in the payable sustance, gamble with iron bar, pays iron bars, that way...

**Comment by graywolf336** [comment]
When this happens it usually means something is wrong with your reward
setup. Most times something gets logged to the console.

**Comment by MrKiller01** [comment]
@Graywolf, if i would tell you that the custom settings were used, are you still convinced that it is a setting in the config? if i never touched that?

**Comment by graywolf336** [comment]
Did you update the settings to reflect the changes to the give command? As
the structure for that changed drastically!

**Comment by MrKiller01** [comment]
I update almost everytime with the reload command, but if i stop and restart the server, the blockage is gone... Maybe a fine(r) tuned default config without giving items, and leave that possibility open, is made upon first use of this plugin could be a step forewards... I'm just guessing, have really no clue to how much time that takes to accomplish, but maybe it's do-able... i hope...

**Comment by graywolf336** [comment]
Post your config file so we can fix your issue.

**Comment by MrKiller01** [comment]
Here it is:
`# Instructions for this configuration file can be found at the BukkitDev page:
# http://dev.bukkit.org/server-mods/casino-slots/pages/info/config/
# If you change the config-version, the defaults will be added. You have been warned.
options:
  debug: false
  config-version: 1.0
  bukkit-version: 2377
  track-statistics: true
  allow-diagonal-winnings: false
  enable-slot-protection: true
  enable-chunk-messages: false
  enable-worldguard-check: false
  towny-checks:
    enabled: false
    only-mayors: true
    no-mayor: You must be a mayor to create a Casino Slot.
    only-towns: true
    no-town: To create a slot you must be part of a town.
    no-ownership: You don't own the plot where that would be at, please make sure you are the owner and then try again.
  chat:
    display-plugin-prefix: true
    plugin-prefix: '[Casino]'
    plugin-prefix-color: '&c&o'
    chat-color: '&a'
  update-checking:
    enabled: true
    channel: bukkit
    time: 120
types:
  default:
    cost: 10
    create-cost: 1000
    controller: note_block
    reel:
    - 42,21
    - 41,12
    - 57,7
    - 46,8
    - 103,9
    - 49,4
    - 3,5
    rewards:
      '42':
        message: Winner - 3 iron blocks! An enchanted iron sword.
        money: 0.0
        action: give 267,16,5 1
      '41':
        message: "Winner - 3 gold blocks! \xe2\u201a\xac300 awarded."
        money: 300.0
      '57':
        message: "Winner - 3 diamond blocks! \xe2\u201a\xac750 awarded."
        money: 750.0
      '46':
        action: kill
        message: Winner -
        money: 0.0
      '103':
        action: give 103 10
        message: Winner - 3 ..melons? Nom.
        money: 0.0
    messages:
      insufficient-permission: Sorry, you can't play this slot.
      insufficient-funds: You can't afford to use this.
      in-use: This slot machine is already in use.
      no-win: No luck this time.
      start: '[cost] removed from your account. Let''s roll!'
      help:
      - 'Instructions:'
      - "Get 3 in a row in order to win. \xe2\u201a\xac10 per spin."
      - "3 iron blocks: \xe2\u201a\xac175"
      - "3 gold blocks: \xe2\u201a\xac300"
      - "3 diamond blocks: \xe2\u201a\xac750"
      - '3 melon blocks: stack of melons'
  actionslot:
    cost: 15
    create-cost: 1000
    controller: stained_clay:5
    reel:
    - 35,3,2
    - 46,1
    - 74,1
    - 87,1
    - 103,1
    - 45,1
    rewards:
      35,3:
        action: goblind
        message: Winne- You can't see now!
        money: 0.0
      '46':
        action: broadcast [player] spent [cost] on a slot machine and won!
        message: Winner - Gefeliciteerd!
        money: 1000.0
      '74':
        action: drugup
        message: Winner - Kids, drugs are bad!
      '87':
        action: fire
        message: Winner - Fire hurts! Don't mess with it.
        money: 0.0
      '103':
        action: give 103 3
        message: Winner - 3 ..melons? Nom.
        money: 0.0
      '45':
        action:
        - gocrazy
        - command give [player] 336 1
        message: Winner - A command has been executed!
        money: 0.0
    messages:
      insufficient-permission: You can't play this one, that's too sad - we really wanted you to win.
      insufficient-funds: You can't afford to use this.
      in-use: This slot machine is already in use.
      no-win: No luck this time.
      start: '[cost] removed from your account. Let''s roll!'
      help:
      - 'Instructions:'
      - "Get 3 in a row in order to win. \xe2\u201a\xac15 per spin."
      - '3 tnt blocks: Death!'
      - '3 on redstone lamps: You go Blind!'
      - '3 melon blocks: stack of melons'
      - '3 redstone: Get drugged'
      - '3 nether brick: Catch on fire'
  cash:
    cost: 1
    create-cost: 10
    reel:
    - 42,10
    - 41,5
    - 57,2
    rewards:
      '42':
        message: Winner!
        money: 25
      '41':
        message: Winner!
        money: 50
      '57':
        message: Winner!
        money: 120
    messages:
      insufficient-funds: You can't afford to use this.
      in-use: This slot machine is already in use.
      no-win: No luck this time.
      start: '[cost] removed from your account. Let''s roll!'
      help:
      - 'Instructions:'
      - Get 3 in a row to win.
      - "3 iron blocks: \xe2\u201a\xac25"
      - "3 gold blocks: \xe2\u201a\xac50"
      - "3 diamond blocks: \xe2\u201a\xac120"
`

**Comment by graywolf336** [comment]
The give commands aren't valid, the syntax got updated. See the release notes: http://dev.bukkit.org/bukkit-plugins/casino-slots/files/20-casino-slots-2-6-0/#w-2-6-0
