### ISSUE TITLE
Missing Towny dependency

### ISSUE THREAD

**Issue by TWSSYesterday** [graywolf336/CasinoSlots#73]
Missing a towny dependency in your internal repo?

**Comment by graywolf336** [comment]
Doesn't look like it: https://repo.craftyn.com/#artifact~internal/com.palmergames.bukkit/Towny Only has one version on there though, I need to see about updating it I guess

**Comment by TWSSYesterday** [comment]
Ever so weird, when compiling, it lacks access to it.

**Comment by graywolf336** [comment]
Can you access it from the website?

**Comment by TWSSYesterday** [comment]
Yeah, so git auth? I did log in when cloning before maven compiling if that makes any difference, if it makes no difference, I still logged in; lol

**Comment by graywolf336** [comment]
Should be able to pull it down without authenticating with the site. Not sure what the issue is :/

**Comment by graywolf336** [comment]
@TWSSYesterday Was you ever able to get it working? I just started fresh on a new workspace environment and it is working fine. Maybe maven got confused on your system?

**Comment by TWSSYesterday** [comment]
Never got it working, got someone else to clone it for me and then mirrored it on my PC lol, unsure of what happened there.
