### ISSUE TITLE
Unable to use custom types outside of 'testing'.

### ISSUE THREAD

**Issue by mibby** [graywolf336/CasinoSlots#84]
CasinoSlots dev 64

@graywolf336 You are unable to use any casino slot type other than 'testing'. 
https://github.com/graywolf336/CasinoSlots/blob/d1107f6538480a7adcd24269b685f0683b2a2fe5/src/main/java/com/craftyn/casinoslots/slot/TypeManager.java#L66

I created 3 new slot types of low, high, and mega stakes. I'm unable to add a casino slot of that type in-game as it reports as being invalid - even after restarting the server. Listing all slot types with ```/casino list types``` only outputs ```testing - cost: 150.54``` despite there being 6 files in the types folder;

- action-example.yml
- default.yml
- high.yml (my custom configuration)
- low.yml (my custom configuration)
- mega.yml (my custom configuration)
- testing.yml 

I also tried deleting action-example, default, and testing yml files because I do not want those slot types, but they reappeared on server restart.

**Comment by graywolf336** [comment]
Let's try after https://github.com/graywolf336/CasinoSlots/commit/d0e78966a578cb88440d1af5e1595f53a4e50a81 :+1:

**Comment by mibby** [comment]
Seems to detect the new types now! Just payout on win breaks.
