### ISSUE TITLE
IRON Blocks Not Giving Reward

### ISSUE THREAD

**Issue by EnthusiastCraftr** [graywolf336/CasinoSlots#90]
Hey, 

Not sure if there is still support for this. 

But when it hits 3 iron blocks it gives an error and does not give reward.

Task #1446 for CasinoSlots v2.6.0-SNAPSHOT-b50 generated an exception
07.02 23:08:20 [Server] INFO java.lang.NumberFormatException: For input string: "267,16,5"
07.02 23:08:20 [Server] INFO at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_121]
07.02 23:08:20 [Server] INFO at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_121]
07.02 23:08:20 [Server] INFO at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_121]
07.02 23:08:20 [Server] INFO at com.craftyn.casinoslots.slot.RewardData.executeAction(RewardData.java:77) ~[?:?]
07.02 23:08:20 [Server] INFO at com.craftyn.casinoslots.slot.RewardData.send(RewardData.java:53) ~[?:?]
07.02 23:08:20 [Server] INFO at com.craftyn.casinoslots.slot.game.ResultsTask.run(ResultsTask.java:56) ~[?:?]
07.02 23:08:20 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot131.jar:git-Spigot-7754231-94b0980]

**Comment by graywolf336** [comment]
You have an invalid value for the rewards. Also, you're using an old version thus I am closing. Here on out I will only be supporting v3-snapshots, I have started some work on ensuring things work properly and without issues in the new version.
